#lang scheme
(define (chooseWord)
  (let ((lst '("programming" "imperative" "functional" "logic" "declarative" "scripting" "prolog" "lexical" "syntactical" "branching")))
       (list-ref lst (random (length lst)))))

(define (play)
  (let ((word (chooseWord)))
       (string->list word)
       (for ([i word])
             (display "_ "))
       (display "\n")
       (guess word)))

(define (guess word)
  (display "\n Guess a letter:")
  (let ((letter (read-line))
        (wrong 0))
       (for ([i word])
         (if (equal? letter i)
             (display letter)
             (display "_ "))))
  (guess word))